apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: mongo-express
        resources:
          requests:
            memory: "60Mi"
            cpu: 150m
          limits:
            memory: "200Mi"
            cpu: 300m
        ports:
          - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-url 
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
