apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: YWRtaW4=
  mongo-password: cmVkaGF0
  mongo-url: bW9uZ29kYjovL2FkbWluOnJlZGhhdEBtb25nby0wLm1vbmdvOjI3MDE3LG1vbmdvLTEubW9uZ286MjcwMTcsbW9uZ28tMi5tb25nbzoyNzAxNy9hZG1pbj9yZXBsaWNhU2V0PXJzMA==
