apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: mongo-statefulset-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongo
  updatePolicy:
    updateMode: "Auto"

